# Generated by Django 2.2.20 on 2022-01-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdmissionformSchoolName', models.CharField(max_length=255, null=True, unique=True)),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Father_Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('DOB', models.DateField()),
                ('Std', models.IntegerField()),
                ('Std_Per', models.CharField(max_length=200)),
                ('Board', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.TextField()),
                ('Established', models.DateField()),
                ('Achievements', models.TextField()),
                ('Sports', models.CharField(max_length=255)),
                ('Image1', models.ImageField(upload_to='media/pics')),
                ('Image2', models.ImageField(upload_to='media/pics')),
                ('Image3', models.ImageField(upload_to='media/pics')),
                ('Image5', models.ImageField(upload_to='media/pics')),
                ('Mobile_No', models.IntegerField(default=None)),
                ('Phone_No', models.IntegerField(default=None)),
                ('Email', models.EmailField(max_length=254)),
                ('Website', models.URLField(default=None)),
                ('City', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('Board', models.CharField(max_length=200)),
                ('Auditorium', models.CharField(max_length=200)),
                ('Infirmary', models.CharField(max_length=200)),
                ('Computer_lab', models.CharField(max_length=200)),
                ('Science_lab', models.CharField(max_length=200)),
                ('Library', models.CharField(max_length=200)),
                ('Cafeteria', models.CharField(max_length=200)),
                ('Hostel', models.CharField(max_length=200)),
                ('Transportation', models.CharField(max_length=200)),
                ('Social_Developement', models.CharField(max_length=255)),
                ('Picnic_Excursions', models.CharField(max_length=255)),
                ('Physical', models.CharField(max_length=255)),
                ('Cultural', models.CharField(max_length=255)),
                ('Arts_Crafts', models.CharField(max_length=255)),
                ('broucher', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='')),
                ('Sector', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Study_Carrier', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('Standard', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='media/pics')),
                ('SchoolName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SchoolName', to='compareschool_app.SchoolDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_Year', models.IntegerField()),
                ('To_Year', models.IntegerField()),
                ('Commerce_Per', models.IntegerField()),
                ('Sciece_per', models.IntegerField()),
                ('PerformanceSchoolName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PerformanceSchoolName', to='compareschool_app.SchoolDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campus1', models.ImageField(blank=True, upload_to='media/pics')),
                ('Campus2', models.ImageField(upload_to='media/pics')),
                ('Campus3', models.ImageField(upload_to='media/pics')),
                ('Class1', models.ImageField(upload_to='media/pics')),
                ('Class2', models.ImageField(upload_to='media/pics')),
                ('Class3', models.ImageField(upload_to='media/pics')),
                ('Lab1', models.ImageField(upload_to='media/pics')),
                ('Lab2', models.ImageField(upload_to='media/pics')),
                ('Area1', models.ImageField(upload_to='media/pics')),
                ('Area2', models.ImageField(upload_to='media/pics')),
                ('Area3', models.ImageField(upload_to='media/pics')),
                ('Sports1', models.ImageField(upload_to='media/pics')),
                ('Sports2', models.ImageField(upload_to='media/pics')),
                ('Sports3', models.ImageField(upload_to='media/pics')),
                ('Sports4', models.ImageField(upload_to='media/pics')),
                ('Sports5', models.ImageField(upload_to='media/pics')),
                ('ImagesSchoolName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImagesSchoolName', to='compareschool_app.SchoolDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Standard', models.CharField(max_length=200)),
                ('Medium', models.CharField(max_length=40)),
                ('Batch', models.CharField(max_length=100)),
                ('Fees', models.IntegerField()),
                ('FeesSchoolName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FeesSchoolName', to='compareschool_app.SchoolDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open_Admission', models.CharField(max_length=50)),
                ('Admission_Info', models.TextField()),
                ('AdmissionSchoolName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdmissionSchoolName', to='compareschool_app.SchoolDetail')),
            ],
        ),
    ]
