# Generated by Django 2.2.20 on 2022-01-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission_form',
            name='AdmissionformSchoolName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
