# Generated by Django 3.2.5 on 2021-12-17 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='schooldetail',
            name='Mobile_No',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='schooldetail',
            name='Phone_No',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='schooldetail',
            name='Website',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='staff',
            name='Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
