# Generated by Django 3.2.5 on 2021-12-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0003_alter_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='Fees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Standard',
            field=models.CharField(max_length=200),
        ),
    ]
