# Generated by Django 3.2.5 on 2021-12-22 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0004_auto_20211217_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooldetail',
            name='Image4',
        ),
    ]
