# Generated by Django 3.2.5 on 2021-12-29 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0006_auto_20211222_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='School_Name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='SchoolName', to='compareschool_app.schooldetail'),
            preserve_default=False,
        ),
    ]
