# Generated by Django 3.2.5 on 2021-12-29 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0007_staff_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='School_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SchoolName', to='compareschool_app.schooldetail'),
        ),
    ]
