# Generated by Django 3.2.5 on 2021-12-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0008_alter_staff_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='School_Name',
        ),
    ]
