# Generated by Django 3.2.5 on 2021-12-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0009_remove_staff_school_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
