# Generated by Django 3.2.5 on 2021-12-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0010_delete_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fees',
        ),
        migrations.DeleteModel(
            name='SchoolDetail',
        ),
    ]
