# Generated by Django 3.2.5 on 2021-12-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compareschool_app', '0011_auto_20211229_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Standard', models.IntegerField()),
                ('Medium', models.CharField(max_length=40)),
                ('Batch', models.CharField(max_length=100)),
                ('Fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.TextField()),
                ('Established', models.DateField()),
                ('Achievements', models.TextField()),
                ('Hostel', models.CharField(max_length=100)),
                ('Sports', models.CharField(max_length=255)),
                ('Image1', models.ImageField(upload_to='media/pics')),
                ('Image2', models.ImageField(upload_to='media/pics')),
                ('Image3', models.ImageField(upload_to='media/pics')),
                ('Image5', models.ImageField(upload_to='media/pics')),
                ('Mobile_No', models.IntegerField(default=None)),
                ('Phone_No', models.IntegerField(default=None)),
                ('Email', models.EmailField(max_length=254)),
                ('Website', models.URLField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Study_Carrier', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('Standard', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='media/pics')),
            ],
        ),
    ]
