# Generated by Django 2.2.20 on 2022-01-01 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0014_auto_20220101_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='School_Name',
        ),
        migrations.AddField(
            model_name='staff',
            name='School_Name_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SchoolName', to='compareschool_app.SchoolDetail'),
        ),
    ]
