# Generated by Django 2.2.20 on 2022-01-03 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0016_auto_20220103_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='FeesSchoolName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FeesSchoolName', to='compareschool_app.SchoolDetail'),
        ),
    ]
