# Generated by Django 2.2.20 on 2022-01-04 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0017_fees_feesschoolname'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetail',
            name='City',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
