# Generated by Django 2.2.20 on 2022-01-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0020_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auditorium', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=11)),
            ],
        ),
    ]
