# Generated by Django 2.2.20 on 2022-01-12 16:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0021_facalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='facalities',
            name='Cafeteria',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facalities',
            name='Computer_lab',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facalities',
            name='Infirmary',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facalities',
            name='Library',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facalities',
            name='SchoolName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Schoolname', to='compareschool_app.SchoolDetail'),
        ),
        migrations.AddField(
            model_name='facalities',
            name='Science_lab',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
    ]
