# Generated by Django 2.2.20 on 2022-01-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0023_auto_20220113_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facalities',
            name='Auditorium',
            field=models.CharField(max_length=11),
        ),
    ]
