# Generated by Django 2.2.20 on 2022-01-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0024_auto_20220113_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facalities',
            name='Cafeteria',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='facalities',
            name='Computer_lab',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='facalities',
            name='Infirmary',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='facalities',
            name='Library',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='facalities',
            name='Science_lab',
            field=models.CharField(max_length=11),
        ),
    ]
