# Generated by Django 2.2.20 on 2022-01-13 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0025_auto_20220113_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facalities',
            name='SchoolName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sn', to='compareschool_app.SchoolDetail'),
        ),
    ]
