# Generated by Django 2.2.20 on 2022-01-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0026_auto_20220113_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facalities',
        ),
    ]
