# Generated by Django 2.2.20 on 2022-01-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0027_delete_facalities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auditorium', models.CharField(max_length=11)),
                ('Infirmary', models.CharField(max_length=11)),
                ('Computer_lab', models.CharField(max_length=11)),
                ('Science_lab', models.CharField(max_length=11)),
                ('Library', models.CharField(max_length=11)),
                ('Cafeteria', models.CharField(max_length=11)),
                ('SchoolName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sn', to='compareschool_app.SchoolDetail')),
            ],
        ),
    ]
