# Generated by Django 2.2.20 on 2022-01-18 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0028_facalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetail',
            name='Auditorium',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schooldetail',
            name='Cafeteria',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schooldetail',
            name='Computer_lab',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schooldetail',
            name='Infirmary',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schooldetail',
            name='Library',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schooldetail',
            name='Science_lab',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Facalities',
        ),
    ]
