# Generated by Django 2.2.20 on 2022-01-18 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0030_auto_20220118_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetail',
            name='Transportation',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schooldetail',
            name='Hostel',
            field=models.CharField(max_length=200),
        ),
    ]
