# Generated by Django 2.2.20 on 2022-01-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0035_auto_20220118_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldetail',
            name='Image1',
            field=models.ImageField(upload_to='media/pics'),
        ),
        migrations.AlterField(
            model_name='schooldetail',
            name='Image2',
            field=models.ImageField(upload_to='media/pics'),
        ),
        migrations.AlterField(
            model_name='schooldetail',
            name='Image3',
            field=models.ImageField(upload_to='media/pics'),
        ),
    ]
