# Generated by Django 2.2.20 on 2022-01-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0037_auto_20220119_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldetail',
            name='Social_Developement',
            field=models.TextField(),
        ),
    ]
