# Generated by Django 2.2.20 on 2022-01-21 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0040_imges'),
    ]

    operations = [
        migrations.AddField(
            model_name='imges',
            name='ImgesSchoolName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImagesSchoolName', to='compareschool_app.SchoolDetail'),
        ),
    ]
