# Generated by Django 2.2.20 on 2022-01-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0041_imges_imgesschoolname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imges',
            new_name='Images',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='ImgesSchoolName',
            new_name='IamgesSchoolName',
        ),
    ]
