# Generated by Django 2.2.20 on 2022-01-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0042_auto_20220121_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='IamgesSchoolName',
            new_name='ImagesSchoolName',
        ),
    ]
