# Generated by Django 2.2.20 on 2022-01-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0043_auto_20220121_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='Standard',
            field=models.CharField(max_length=200),
        ),
    ]
