# Generated by Django 2.2.20 on 2022-01-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0044_auto_20220121_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetail',
            name='broucher',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
    ]
