# Generated by Django 2.2.20 on 2022-01-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0045_schooldetail_broucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broucher', models.FileField(null=True, upload_to='files/', verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='schooldetail',
            name='broucher',
        ),
    ]
