# Generated by Django 2.2.20 on 2022-01-22 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0046_auto_20220122_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='broucher',
            name='BroucherSchoolName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broucheschoolname', to='compareschool_app.SchoolDetail'),
        ),
    ]
