# Generated by Django 2.2.20 on 2022-01-23 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0048_auto_20220122_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetail',
            name='Board',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
