# Generated by Django 2.2.20 on 2022-01-24 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0049_schooldetail_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetail',
            name='Sector',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schooldetail',
            name='broucher',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name=''),
        ),
    ]
