# Generated by Django 2.2.20 on 2022-01-24 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0050_auto_20220124_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetail',
            name='Performance',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
