# Generated by Django 2.2.20 on 2022-01-24 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0051_schooldetail_performance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooldetail',
            name='Performance',
        ),
    ]
