# Generated by Django 2.2.20 on 2022-01-24 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0052_remove_schooldetail_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Performance', models.TextField()),
                ('PerformanceSchoolName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PerformanceSchoolName', to='compareschool_app.SchoolDetail')),
            ],
        ),
    ]
