# Generated by Django 2.2.20 on 2022-01-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0054_auto_20220124_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='Commerce_Per',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='Sciece_per',
            field=models.IntegerField(),
        ),
    ]
