# Generated by Django 2.2.20 on 2022-01-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compareschool_app', '0055_auto_20220124_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
